[project]
name = "timelock-interpreter"
authors = ["Blockchain Escrow Team"]
description = "A smart contract for creating time-locked escrow and asset management"
telemetry = false
requirements = []
[contracts.timelock-escrow]
path = "contracts/timelock-escrow.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
